<?php

namespace Database\Seeders;

use App\Models\AccountGroup;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LedgerAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ledger_accounts')->insert([
            // ASSET ACCOUNTS (101-199)
            ['id' => 101, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Cash'],
            ['id' => 102, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Petty cash'],
            ['id' => 103, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Cash equivalents'],
            ['id' => 104, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Short-term investments'],
            ['id' => 106, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accounts receivable'],
            ['id' => 107, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Allowance for doubtful accounts'],
            ['id' => 109, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Interest receivable'],
            ['id' => 110, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Rent receivable'],
            ['id' => 111, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Notes receivable'],
            ['id' => 119, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Merchandise inventory'],
            ['id' => 124, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Office supplies'],
            ['id' => 128, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Prepaid insurance'],
            ['id' => 129, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Prepaid interest'],
            ['id' => 131, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Prepaid rent'],
            ['id' => 141, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Long-term Investments'],
            ['id' => 151, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Automobiles'],
            ['id' => 152, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation- Automobiles'],
            ['id' => 153, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Trucks'],
            ['id' => 154, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation-Trucks'],
            ['id' => 159, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Library'],
            ['id' => 160, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation-Library'],
            ['id' => 161, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Furniture'],
            ['id' => 162, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation-Furniture'],
            ['id' => 163, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Office Equipment'],
            ['id' => 164, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation-Office equipment'],
            ['id' => 169, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Machinery'],
            ['id' => 170, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation-Machinery'],
            ['id' => 175, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Building'],
            ['id' => 176, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation-Building'],
            ['id' => 179, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Land improvements'],
            ['id' => 180, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation-Land improvements'],
            ['id' => 183, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Land'],
            ['id' => 185, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Mineral deposit'],
            ['id' => 186, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated depreciation-Mineral deposit'],
            ['id' => 191, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Patents'],
            ['id' => 192, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Leasehold'],
            ['id' => 193, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Franchise'],
            ['id' => 194, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Copyrights'],
            ['id' => 195, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Leaseholds improvements'],
            ['id' => 196, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Licenses'],
            ['id' => 197, 'account_group_id' => AccountGroup::ASSETS, 'name' => 'Accumulated amortization'],
            // LIABILITY ACCOUNTS (201-299)
            ['id' => 201, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Accounts payable'],
            ['id' => 202, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Insurance payable'],
            ['id' => 203, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Interest payable'],
            ['id' => 204, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Legal fees payable'],
            ['id' => 207, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Office salaries payable'],
            ['id' => 208, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Rent payable'],
            ['id' => 209, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Salaries payable'],
            ['id' => 210, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Wages payable'],
            ['id' => 211, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Accrued payroll payable'],
            ['id' => 214, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Estimated warranty liability'],
            ['id' => 215, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Income taxes payable'],
            ['id' => 216, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Common dividend payable'],
            ['id' => 217, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Preferred dividend payable'],
            ['id' => 218, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'State unemployment taxes payable'],
            ['id' => 219, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Employee federal income taxes payable'],
            ['id' => 221, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Employee medical insurance payable'],
            ['id' => 222, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Employee retirement program payable'],
            ['id' => 223, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Employee union dues payable'],
            ['id' => 224, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Federal unemployment taxes payable'],
            ['id' => 225, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'FICA taxes payable'],
            ['id' => 226, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Estimated vacation pay liability'],
            ['id' => 230, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Unearned consulting fees'],
            ['id' => 231, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Unearned legal fees'],
            ['id' => 232, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Unearned property management fees'],
            ['id' => 235, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Unearned janitorial revenue'],
            ['id' => 238, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Unearned rent'],
            ['id' => 240, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Short-term notes payable'],
            ['id' => 245, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Notes payable'],
            ['id' => 251, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Long-term notes payable'],
            ['id' => 253, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Long-term lease liability'],
            ['id' => 255, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Bonds payable'],
            ['id' => 258, 'account_group_id' => AccountGroup::LIABILITIES, 'name' => 'Deferred income tax liability'],
            // EQUITY ACCOUNTS (301-399)
            ['id' => 301, 'account_group_id' => AccountGroup::EQUITY, 'name' => "Owner's Capital"],
            ['id' => 302, 'account_group_id' => AccountGroup::EQUITY, 'name' => "Owner's Withdrawals"],
            ['id' => 307, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Common stock, par value'],
            ['id' => 308, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Common stock, no par value'],
            ['id' => 309, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Common stock, stated value'],
            ['id' => 310, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Common stock dividend distributable'],
            ['id' => 311, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Paid-in capital in excess of par value, Common stock'],
            ['id' => 312, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Paid-in capital in excess of stated value, No- par common stock'],
            ['id' => 313, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Paid-in capital from retirement of common stock'],
            ['id' => 314, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Paid in capital, Treasury stock'],
            ['id' => 315, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Preferred stock'],
            ['id' => 316, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Paid-in capital in excess of par value, Preferred stock'],
            ['id' => 318, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Retained earnings'],
            ['id' => 319, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Cash dividends'],
            ['id' => 320, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Stock dividends'],
            ['id' => 321, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Treasury stock, Common'],
            ['id' => 322, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Unrealized gain-Equity'],
            ['id' => 323, 'account_group_id' => AccountGroup::EQUITY, 'name' => 'Unrealized loss-Equity'],
            // REVENUE ACCOUNTS (401-499)
            ['id' => 401, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Sales'],
            ['id' => 402, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Sales returns and allowances'],
            ['id' => 403, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Sales discounts'],
            ['id' => 405, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Commissions earned'],
            ['id' => 406, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Rent revenue'],
            ['id' => 407, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Dividends revenue'],
            ['id' => 408, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Earnings from investments in "blank"'],
            ['id' => 409, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Interest revenue'],
            ['id' => 410, 'account_group_id' => AccountGroup::REVENUE, 'name' => 'Sinking fund earnings'],
            // EXPENSE ACCOUNTS (501-599)
            ['id' => 501, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Amortization expense'],
            ['id' => 502, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depletion expense'],
            ['id' => 503, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Automobiles'],
            ['id' => 504, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Building'],
            ['id' => 505, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Furniture'],
            ['id' => 506, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Land improvements'],
            ['id' => 507, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Library'],
            ['id' => 508, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Machinery'],
            ['id' => 509, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Mineral deposit'],
            ['id' => 510, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Office equipment'],
            ['id' => 511, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Depreciation expense-Trucks'],
            ['id' => 520, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Office salaries expense'],
            ['id' => 521, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Sales salaries expense'],
            ['id' => 522, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Salaries expense'],
            ['id' => 523, 'account_group_id' => AccountGroup::EXPENSES, 'name' => '"Blank" wages expense'],
            ['id' => 524, 'account_group_id' => AccountGroup::EXPENSES, 'name' => "Employees' benefits expense"],
            ['id' => 525, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Payroll taxes expense'],
            ['id' => 530, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Cash over and Short'],
            ['id' => 531, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Discounts lost'],
            ['id' => 532, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Factoring fee expense'],
            ['id' => 533, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Interest expense'],
            ['id' => 535, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Insurance expense-Delivery equipment'],
            ['id' => 536, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Insurance expense-Office equipment'],
            ['id' => 540, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Rent expense'],
            ['id' => 541, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Rent expense-Office space'],
            ['id' => 542, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Rent expense-Selling space'],
            ['id' => 543, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Press rental expense'],
            ['id' => 544, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Truck rental expense'],
            ['id' => 545, 'account_group_id' => AccountGroup::EXPENSES, 'name' => '"Blank" rental expense'],
            ['id' => 550, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Office supplies expense'],
            ['id' => 551, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Store supplies expense'],
            ['id' => 552, 'account_group_id' => AccountGroup::EXPENSES, 'name' => '"Blank" supplies expense'],
            ['id' => 555, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Advertising expense'],
            ['id' => 556, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Bad debts expense'],
            ['id' => 557, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Blueprinting expense'],
            ['id' => 558, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Boat expense'],
            ['id' => 559, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Collection expense'],
            ['id' => 561, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Concessions expense'],
            ['id' => 562, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Credit card expense'],
            ['id' => 563, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Delivery expense'],
            ['id' => 564, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Dumping expense'],
            ['id' => 566, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Equipment expense'],
            ['id' => 567, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Food and drinks expense'],
            ['id' => 568, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Gas and oil expense'],
            ['id' => 571, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'General and administrative expense'],
            ['id' => 572, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Janitorial expense'],
            ['id' => 573, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Legal fees expense'],
            ['id' => 574, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Mileage expense'],
            ['id' => 576, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Miscellaneous expense'],
            ['id' => 577, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Mower and tool expense'],
            ['id' => 578, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Operating expense'],
            ['id' => 579, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Organization expense'],
            ['id' => 580, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Permits expense'],
            ['id' => 581, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Postage expense'],
            ['id' => 582, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Property taxes expense'],
            ['id' => 583, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Repairs expense'],
            ['id' => 584, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Selling expense'],
            ['id' => 585, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Telephone expense'],
            ['id' => 587, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Travel and entertainment expense'],
            ['id' => 590, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Utilities expense'],
            ['id' => 591, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Warranty expense'],
            ['id' => 595, 'account_group_id' => AccountGroup::EXPENSES, 'name' => 'Income taxes expense']
        ]);
    }
}
